### ISSUE TITLE
NAs in tr2g.tsv after `get_velocity_files()`

### ISSUE THREAD

**Issue by palfalvi** [BUStools/BUSpaRse#11]
Hi,

I would like to use the `get_velocity_files()` function to build indices, but I ran into an error. I use a newly assembled and annotated genome, so the labels are "scaffold_1, scaffold_2" for genome and "G1.1, G1.2" for transcripts, where GX is the gene and .Y is the isoform. 
The code runs without a problem using a gtf file (contains gene, exon, CDS, ... fields) and a DNAStringSet for the genome input with the following:

`get_velocity_files("annotation.gtf", L= 91, Genome=genome, out_path=".", isoform_action = "separate")`

It generates all files, however the `tr2g.tsv` file looks like this:

```
G1.1.-I NA
G1.1.-I1        NA
G1.1.-I2        NA
G1.1.-I3        NA
G1.2.-I NA
G1.2.-I1        NA
G1.2.-I2        NA
G1.2.-I3        NA
G1.3.-I NA
G1.3.-I1        NA
G1.3.-I2        NA
G1.3.-I3        NA
...
```

Additionally the `cDNA_tx_to_capture.txt` file is empty. 

I do not know if I did something wrong or it could be maybe due to the too minimalist scaffold/gene names?

Thanks for the help in advance! 

Cheers,
Gergo

**Comment by lambdamoses** [comment]
In the current version, `get_velocity_files` by default removes what's not a standard chromosome, which includes scaffolds and haplotypes, to cater to existing genome annotations of model organisms. Try set the argument `chrs_only = FALSE` and see if the problem is resolved.

**Comment by palfalvi** [comment]
Thank you, finally that did the trick!
