### ISSUE TITLE
Change the default value to the chrs_only argument in the get_velocity_files function

### ISSUE THREAD

**Issue by jma1991** [BUStools/BUSpaRse#12]
Not so much an issue, but rather a suggestion. It might be better if the _chrs_only_ argument in the _get_velocity_files_ function is set to FALSE by default. I have been following the kallisto and bustools workflow for RNA velocity analysis and I kept finding a single feature in my count matrix with NA as the gene identifier. After some investigation, I realised that multiple NA values were present in the gene identifier column of the tr2g.tsv file because these particular genes were not on the primary chromosomes. The counts from these transcripts were combined into a single gene feature by bustools with NA as the gene identifier.

**Comment by lambdamoses** [comment]
The `chrs_only` argument was intended to remove scaffolds and haplotypes if you don't want them. I did not expect the NAs. I'll fix the NA issue with this argument is TRUE but need to debate whether the default should be FALSE.

**Comment by jma1991** [comment]
> The `chrs_only` argument was intended to remove scaffolds and haplotypes if you don't want them. I did not expect the NAs. I'll fix the NA issue with this argument is TRUE but need to debate whether the default should be FALSE.

Ah I didn’t realise the NA features were unintended. Yes, if the NA features are removed I agree that leaving it on by default would be better. Thanks.

**Comment by lambdamoses** [comment]
This problem occurred because the scaffolds were not removed from the GRanges annotation, which is used to get the flanked introns. Now the scaffolds are removed from the annotation if `chrs_only = TRUE` and should solve this problem.
