### ISSUE TITLE
Error in fill_cell_gene

### ISSUE THREAD

**Issue by jmzvillarreal** [BUStools/BUSpaRse#14]
Hi all, 
Sorry for the basic question but I am stuck in this strep:I am generating the sparse matrix from kallisto bus files.. Everything seems ok but I get this error:

Error in fill_cell_gene(bus_fn, kallisto_out_path, tr2g, est_ncells, est_ngenes,  : 
  Index out of bounds: [index='gene']
Thanks in advance,
Jaime.

**Comment by lambdamoses** [comment]
This part of this package was written when kallisto bustools were experimental. You need to use bustools to convert the binary bus file into text first to use this function. But now a more efficient C++ implementation is available in bustools and you should use that instead unless you want to experiment on the fill_cell_gene function for other purposes.
