### ISSUE TITLE
TCC sparse matrix

### ISSUE THREAD

**Issue by Simon-Coetzee** [BUStools/BUSpaRse#2]
Is it possible, or still advisable, to import the bus data as a TCC matrix for differential expression / clustering like in previous papers using kallisto for scrna-seq. I notice that the make_sparse_matrix function requires gene annotation, and puts out a gene x cell matrix.

**Comment by lambdamoses** [comment]
It is advisable. I'm implementing the TCC features right now and it will be made available in a few days.

**Comment by lambdamoses** [comment]
Here you go. The user interface has changed a bit. The `make_sparse_matrix` function can now make both the gene count matrix and the TCC matrix at the same time, and you can choose whether to only make the gene count matrix or only the TCC matrix.
