### ISSUE TITLE
make_sparse_matrix excludes barcodes even with whitelist=NULL

### ISSUE THREAD

**Issue by willtownes** [BUStools/BUSpaRse#3]
I have bus file output from running kallisto version 0.45.1 on the Klein 2015 inDrops dataset (SRA ID: SRR1784314). When I create the gene counts matrix using make_sparse_matrix function, I noticed that of the 342,010 unique barcodes in the original bus file, a total of 8,212 barcodes were not included in the columns of the sparse matrix output. Of these excluded barcodes, I found that the vast majority contained a single UMI, but some contained as many as 5-16 UMIs. Why are these barcodes being removed? In the function documentation it says all barcodes should be included.

**Comment by lambdamoses** [comment]
Are you making a gene count matrix or a TCC matrix? The BUS file contains information of which UMI of which barcode maps to which equivalence class (EC). When making a gene count matrix, the EC's need to be collapsed into genes. In case when the same UMI maps to multiple EC's that maps to multiple genes, the intersection of genes is taken when collapsing the EC's. If the intersection is empty (e.g. the UMI maps to an EC with genes A and B, as well as another EC with genes C and D, so the intersection between the two EC's is empty), then the UMI will be discarded. The vast majority of barcodes are from empty droplets, and some empty droplets may only have reads from UMIs with empty intersection of genes, and as a result, those reads are discarded, so will those barcodes.

If you are making a TCC matrix, in case one UMI maps to multiple EC's, the intersection of transcripts in those EC's are used. For instance, if an UMI maps to an EC with transcripts A, B, and C, and another EC with transcripts A, C, and D, then this UMI will be assigned to an equivalence class with only A and C. If that intersection is empty, then this UMI will be discarded. If all UMIs of a barcode have empty intersection, then the barcode will be discarded. 

So it's not really all barcodes. Thank you for pointing out the mistake in the documentation. I'll update the documentation to clarify.

**Comment by willtownes** [comment]
@lambdamoses thanks for the clarification, it makes sense now. I was working with the gene counts matrix. I checked a couple of examples of the excluded barcodes and they matched the criteria you describe- there were no UMIs such that the intersection of genes across equivalence classes was non-empty.
