### ISSUE TITLE
get_velocity_files function for multiple species 

### ISSUE THREAD

**Issue by rfarouni** [BUStools/BUSpaRse#4]
Hi,
I would like to build a kallisto index for a human/mouse with flanked introns. Can  *get_velocity_files* function be used for multiple species?

Thanks in advance!

**Comment by lambdamoses** [comment]
The function was built and tested on single species. However, it wouldn't take much more to do multiple species. You can concatenate the human and mouse gene annotations and the human and mouse genomes (make sure that human chromosomes are named differently from mouse chromosomes and set `style = "other"`). Alternatively, you can generate the required files with two separate calls of `get_velocity_files` for human and mouse respectively, and then concatenate the resulting files. If using Ensembl gene and transcript IDs, the human IDs will certainly be different from the mouse IDs, so those files can be concatenated directly without modifying anything.
