### ISSUE TITLE
package ‘BUSpaRse’ is not available (for R version 3.6.1) 

### ISSUE THREAD

**Issue by bsmith030465** [BUStools/BUSpaRse#5]
Hi,

I was trying to install this package, but get an error that it is not available for R 3.6.1. Can I install this package by another method?

> BiocManager::install("BUSpaRse")
Bioconductor version 3.9 (BiocManager 1.30.4), R 3.6.1 (2019-07-05)
Installing package(s) 'BUSpaRse'
Update old packages: 'mgcv'
Update all/some/none? [a/s/n]: 
n
Warning message:
package ‘BUSpaRse’ is not available (for R version 3.6.1) 

> library("BUSpaRse")
Error in library("BUSpaRse") : there is no package called ‘BUSpaRse’

**Comment by lambdamoses** [comment]
This package is on Bioconductor 3.10, not 3.9. So you should install the devel version of Bioconductor to install this package: `BiocManager::install(version = “devel”)`. Alternatively, install from GitHub by `devtools::install_github(“BUStools/BUSpaRse”)`. Bioconductor 3.10 will become the release version on October 30.
