### ISSUE TITLE
spliced assay is not similar to RNA assay in Seurat-velocity obj 

### ISSUE THREAD

**Issue by hmassalha** [BUStools/BUSpaRse#6]
Hi, 
I am running the Kallisto pipeline to make the velocity analysis for my data and I made a Seurat obj containing the velocity sf, uf, spliced and the unspliced assays. The cells were filtered based on a list of filtered cell names from an independent Surat obj which I prepared using zUMIs for my entire project.
As I know, spliced assay and RNA assay are the same. In my data, I see they are different! any reason why is that? 
I have the same cells, but in the spliced assay, I have smeared expression compare to RNA assay. I think this affects the final velocity map.  I used the same GTF file for Kallisto and normal Seurat pipeline, the same cells,... except for the genome file to include introns mapping.
Any suggestion? 

Thanks, HM,

**Comment by lambdamoses** [comment]
The gene count matrix from STAR is not the same as the spliced matrix from velocyto. How is your data quality? When you are removing empty droplets, what proportion of UMIs come from empty droplets and what proportion from what you think are real cells? I did not see the smeared phenomenon in the 10x mouse neuron 10k dataset and another 10x dataset that have decent quality, but I also got the smeared problem when analyzing a dataset (also 10x, unpublished) with poor quality, like over 50% of UMIs from empty droplets (probably many cells died when the library was prepared). I wonder if the smearing problem is related to data quality.

**Comment by lambdamoses** [comment]
Sorry, it was probably not just the problem with the data. There was an embarrassing bug in this package when extracting flanked introns of genes on the minus strand, partially fixed with Bioc 3.12 version of this package but more fully fixed with issue #13.
