### ISSUE TITLE
read_count_output doesn't work.

### ISSUE THREAD

**Issue by methornton** [BUStools/BUSpaRse#7]
Hello!  I am trying to use BUSpaRse to go from kallistobus to Seurat in R.  I was hoping that I could use 'read_count_output' instead of going backwards with the 1k PBMC vignette, 'https://bustools.github.io/BUS_notebooks_R/10xv3.html'.

I ran kallisto and bustools similarly to the manual here, 'https://www.kallistobus.tools/getting_started'

kallisto
`kallisto bus -i /dataVolume/genomes/kallisto_bus/GRCm38_Ensembl99/Mus_musculus.GRCm38.cdna.all.idx -o bus_output/ -x 10xv3 -t 4 WT1_1_R1.fastq.gz WT1_1_R2.fastq.gz`

bustools
`bustools correct -w /dataVolume/genomes/kallisto_bus/10xv3_whitelist.txt -p output.bus | bustools sort -T tmp/ -t 32 -p - | bustools count -o genecount/WT1_1 -g /dataVolume/genomes/kallisto_bus/Ensembl99_transcripts_to_genes.txt -e matrix.ec -t transcripts.txt --genecounts -`

BUSpaRse
library(BUSpaRse)

```
> data <- read_count_output("/dataVolume/data/Turcatel/04Feb20/raw_data/GT1_GT1/bus_output/genecount", "WT1_1")
Error in fread(paste0(dir, "/", name, ge), header = FALSE) : 
  File '/dataVolume/data/Turcatel/04Feb20/raw_data/GT1_GT1/bus_output/WT1_1.ec.txt' does not exist or is non-readable. getwd()=='/dataVolume/data/Turcatel/04Feb20/raw_data/GT1_GT1/bus_output/genecount'
```
I guess it is looking for the *.ec file in the directory above.  I will reprocess the data with the other vignette, 'https://bustools.github.io/BUS_notebooks_R/10xv3.html/'  I forsee some additional difficulty as the vignette loads a file "output.sorted.txt" which isn't generated by bustools in the getting started vignette.  Please let me know if there is a workaround.  This will probably help others who will have the same problem.  Thanks

**Comment by lambdamoses** [comment]
If you are reading a gene count matrix, then set `tcc = FALSE` here. Perhaps in the next release, for Bioconductor 3.11, I'll change the default to `tcc = FALSE` since it seems that most people use gene count matrices. The TCC matrix output does have a *.ec.txt file, which is like *.genes.txt for gene count matrix, since in TCC matrices, the rows are equivalence matrices (EC) rather than genes.

**Comment by methornton** [comment]
Hello!  That worked.  'tcc=FALSE' was listed in the docs as default, but in the examples changed.
```
Arguments:

     dir: Directory with the bustools count outputs.

    name: The files in the output directory should be "name".mtx,
          "name".genes.txt, and "name".barcodes.txt.

     tcc: Logical, whether the matrix of interest is a TCC matrix.
          Defaults to 'FALSE'.

I appreciate your help! Thank you!

```
